const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const swaggerDefinition = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    openapi: '3.0.0', // Specification (optional, defaults to swagger: '2.0')
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
      contact: {
        name: 'Vo Anh Tuan'
      },
      servers: ["http://localhost:3000"]
    },
    basePath: '/'
  },
  apis: ['./api/routes/users.js', './api/routes/products.js'],
};
const specs = swaggerJsdoc(swaggerDefinition);

module.exports = (app) => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
}